theme: jekyll-theme-minimal
title: Charles R Smith

sidebar:
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/charles-smith-econ/"
    icon: "🔗"  # or use an HTML icon or emoji like "🔗" or "💼"
